const initalContainers = [
  {
    name: "A",
    image: null,
    showColor: true,
    isDraggableDisabled: true,
    isDroppableDisabled: false,
  },
  {
    name: "B",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "C",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "D",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "E",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "F",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "G",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "H",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "I",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "J",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "K",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "L",
    image: null,
    showColor: false,
    isDraggableDisabled: true,
    isDroppableDisabled: true,
  },
  {
    name: "M",
    image: "/Pose/Pose1.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "N",
    image: "/Pose/Pose2.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "O",
    image: "/Pose/Pose3.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "P",
    image: "/Pose/Pose4.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "Q",
    image: "/Pose/Pose5.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "R",
    image: "/Pose/Pose6.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "S",
    image: "/Pose/Pose7.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "T",
    image: "/Pose/Pose8.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "U",
    image: "/Pose/Pose9.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "V",
    image: "/Pose/Pose10.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "W",
    image: "/Pose/Pose11.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
  {
    name: "X",
    image: "/Pose/Pose12.JPG",
    showColor: false,
    isDraggableDisabled: false,
    isDroppableDisabled: true,
  },
];

const colorNames = ["blue", "red"];
const colorChoices = ["#25b3f5", "#ff6961"];
const colorBorderChoices = ["border-[#25b3f5]", "border-[#ff6961]"];
const mouseColor = ["cursor-blueCursorPointer", "cursor-redCursorPointer"];

const initalSolutionOrder = [
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
];

export {
  colorBorderChoices,
  colorChoices,
  colorNames,
  initalContainers,
  initalSolutionOrder,
  mouseColor,
};
