import { CommonPotionSchema } from "@/types";
import { MagicType, PrimaryAttribute, Rarity } from "@prisma/client";
import { z } from "zod";

export const commonPotions: z.infer<typeof CommonPotionSchema> = [
  {
    id: 1,
    name: "Potion of False Life",
    rarity: "COMMON",
    type: "ARCANE",
    primaryAttribute: "NECROMANCY",
    description: "it gives temporary hp",
    abjuration: 6,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 5,
    illusion: 0,
    necromancy: 0,
    transmutation: 0,
  },
  {
    id: 2,
    name: "Potion of Minor Healing",
    rarity: "COMMON",
    type: "ARCANE",
    primaryAttribute: "NECROMANCY",
    description: "heal 1d4 + 2 hp",
    abjuration: 3,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 10,
    illusion: 4,
    necromancy: 0,
    transmutation: 0,
  },
];

export const playerIngredients = [
  {
    id: "1",
    name: "Evergreen Herb",
    rarity: Rarity["COMMON"],
    type: MagicType["PRIMAL"],
    quantity: 1,
    userId: "empty",
    primaryAttribute: PrimaryAttribute["NECROMANCY"],
    description: "It's good for healing",
    abjuration: 3,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 0,
    illusion: 0,
    necromancy: 5,
    transmutation: 0,
  },
  {
    id: "2",
    name: "Evergreen Mushroom",
    description: "It's good for healing",
    rarity: Rarity["COMMON"],
    type: MagicType["PRIMAL"],
    quantity: 1,
    userId: "empty",
    primaryAttribute: PrimaryAttribute["NECROMANCY"],
    abjuration: 0,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 0,
    illusion: 4,
    necromancy: 10,
    transmutation: 0,
  },
  {
    id: "3",
    name: "Ghoulsprout",
    description: "It's good for necromancy",
    rarity: Rarity["COMMON"],
    type: MagicType["PRIMAL"],
    quantity: 1,
    userId: "empty",
    primaryAttribute: PrimaryAttribute["NECROMANCY"],
    abjuration: 0,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 0,
    illusion: 0,
    necromancy: 10,
    transmutation: 3,
  },
];
