export const potionData = [
  {
    id: 1,
    name: "Potion of False Life",
    description: "it gives temporary hp",
    abjuration: 6,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 5,
    illusion: 0,
    necromancy: 0,
    transmutation: 0,
  },
  {
    id: 2,
    name: "Potion of Minor Healing",
    description: "heal 1d4 + 2 hp",
    abjuration: 3,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 10,
    illusion: 4,
    necromancy: 0,
    transmutation: 0,
  },
];

export const playerIngredients = [
  {
    id: 1,
    name: "Evergreen Herb",
    description: "It's good for healing",
    abjuration: 3,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 5,
    illusion: 0,
    necromancy: -7,
    transmutation: 0,
  },
  {
    id: 2,
    name: "Evergreen Mushroom",
    description: "It's good for healing",
    abjuration: 0,
    conjuration: 0,
    divination: 0,
    enchantment: 0,
    evocation: 5,
    illusion: 4,
    necromancy: -3,
    transmutation: 0,
  },
  {
    id: 3,
    name: "Ghoulsprout",
    description: "It's good for necromancy",
    abjuration: 3,
    conjuration: 0,
    divination: 0,
    enchantment: -6,
    evocation: 0,
    illusion: 0,
    necromancy: 7,
    transmutation: 0,
  },
];