export const allMetals = {
  copper: {
    name: "copper",
    rarity: "uncommon",
    hiddenValue: "purity",
    hardness: 3,
    magicAffinity: 1,
    purity: 1,
  },
  tin: {
    name: "tin",
    rarity: "uncommon",
    hiddenValue: "magicAffinity",
    hardness: 4,
    magicAffinity: 4,
    purity: 1,
  },
  lead: {
    name: "lead",
    rarity: "uncommon",
    hiddenValue: "purity",
    hardness: 7,
    magicAffinity: 2,
    purity: 2,
  },
  brass: {
    name: "brass",
    rarity: "uncommon",
    hiddenValue: undefined,
    hardness: 2,
    magicAffinity: 3,
    purity: 11,
  },
  gold: {
    name: "gold",
    rarity: "uncommon",
    hiddenValue: undefined,
    hardness: 1,
    magicAffinity: 6,
    purity: 6,
  },
  platinum: {
    name: "platinum",
    rarity: "uncommon",
    hiddenValue: undefined,
    hardness: 6,
    magicAffinity: 7,
    purity: 12,
  },
  iron: {
    name: "iron",
    rarity: "uncommon",
    hiddenValue: undefined,
    hardness: 3,
    magicAffinity: 2,
    purity: 2,
  },
  bronze: {
    name: "bronze",
    rarity: "uncommon",
    hiddenValue: "hardness",
    hardness: 7,
    magicAffinity: 5,
    purity: 2,
  },
  steel: {
    name: "steel",
    rarity: "uncommon",
    hiddenValue: "magicAffinity",
    hardness: 10,
    magicAffinity: 4,
    purity: 4,
  },
  silver: {
    name: "silver",
    rarity: "uncommon",
    hiddenValue: undefined,
    hardness: 2,
    magicAffinity: 9,
    purity: 2,
  },
  adamant: {
    name: "adamant",
    rarity: "rare",
    hiddenValue: undefined,
    hardness: 20,
    magicAffinity: 11,
    purity: 8,
  },
  coldiron: {
    name: "coldiron",
    rarity: "rare",
    hiddenValue: undefined,
    hardness: 10,
    magicAffinity: 15,
    purity: 20,
  },
  mithril: {
    name: "mithril",
    rarity: "rare",
    hiddenValue: undefined,
    hardness: 10,
    magicAffinity: 20,
    purity: 10,
  },
  earthgem: {
    name: "earthgem",
    rarity: "rare",
    hiddenValue: undefined,
    hardness: 40,
    magicAffinity: 46,
    purity: 38,
  }
};
export const RARE_METALS = [
  {
    name: "adamant",
    rarity: "rare",
    hidden: true,
    hiddenValue: undefined,
    hardness: 20,
    magicAffinity: 11,
    purity: 8,
  },
  {
    name: "coldiron",
    rarity: "rare",
    hidden: true,
    hiddenValue: undefined,
    hardness: 10,
    magicAffinity: 15,
    purity: 20,
  },
  {
    name: "mithril",
    rarity: "rare",
    hidden: true,
    hiddenValue: undefined,
    hardness: 10,
    magicAffinity: 20,
    purity: 10,
  },
];

const EMPTY_METAL = {
  name: "Empty",
  rarity: "empty",
  hiddenValue: undefined,
  hardness: 0,
  magicAffinity: 0,
  purity: 0,
};
export const EMPTY_METAL_MIXTURE = [EMPTY_METAL, EMPTY_METAL, EMPTY_METAL];
